-- (56) ROWNUM: 상단 행 출력. 
SELECT EMPNO, ENAME, JOB, SAL
FROM EMP
WHERE ROWNUM <= 5
ORDER BY SAL DESC;

-- (57)
SELECT EMPNO, ENAME, JOB, SAL
FROM EMP
ORDER BY DEPTNO, SAL DESC FETCH FIRST 5 ROW ONLY;
